export const LOG_USER_IN_PENDING = 'LOG_USER_IN_PENDING';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_ERROR = 'LOG_USER_ERROR';
export const LOGIN_ATTEMPTED = 'LOGIN_ATTEMPTED';
export const SHOW_LOADER ='SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';